### PR TITLE
Clean Data from Python organizers into DU Format

### PR DESCRIPTION
**Pull request by SangamSwadiK**
**Issue**: #2 

**What does this PR do?** 
Adds a notebook to clean data from Python organizers into DU format.
The notebook can be run once the data from Python organizers have been imported and the path is set.

@reshamas  Please let me know in case of changes or suggestions.

Thanks.

### CODE REVIEW

**Comment by reshamas** [comment]
@SangamSwadiK Thanks for this!
I can't see the full notebook right now on GitHub.
Can you output the csv file and include it here in the PR?

**Comment by SangamSwadiK** [comment]
> @SangamSwadiK Thanks for this!
> I can't see the full notebook right now on GitHub.
> Can you output the csv file and include it here in the PR?

Hi, Sure. I'm sleeping right now. Will do it tomorrow morning.

**Comment by SangamSwadiK** [comment]
> @SangamSwadiK Thanks for this! I can't see the full notebook right now on GitHub. Can you output the csv file and include it here in the PR?

Hi, I've added the CSV file as well.
Thanks.

**Comment by reshamas** [comment]
@SangamSwadiK 
Best practices in coding is that folders do not have names with spaces in them "Notebooks to clean data in DU Format". Can you rename to: `notebooks`

**Review by reshamas — CHANGES_REQUESTED** [review]
rename folder following best practices for Unix and software engineering.

**Pull request merged**
